# Generated by Django 5.2.5 on 2026-01-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_academicsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='current_year',
            field=models.CharField(help_text='Example: 2025-26', max_length=20, unique=True),
        ),
    ]
