# Generated by Django 5.2.5 on 2026-01-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_academicsession_current_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshops',
            old_name='benefits',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='workshops',
            old_name='mode',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='workshops',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='workshops',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='workshops',
            name='location',
        ),
        migrations.RemoveField(
            model_name='workshops',
            name='schedule',
        ),
    ]
