# Generated by Django 5.2.5 on 2026-01-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_benefits_workshops_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshops',
            name='url',
        ),
        migrations.AddField(
            model_name='workshops',
            name='register_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workshops',
            name='resource_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='fees',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
