# Generated by Django 5.2.5 on 2026-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_workshops_url_workshops_register_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchrepresentative',
            name='tenure',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='workshops',
            name='photo',
            field=models.ImageField(blank=True, upload_to='workshops/'),
        ),
    ]
