# Generated by Django 5.2.5 on 2026-01-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_branchrepresentative_tenure_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lectures',
        ),
        migrations.DeleteModel(
            name='PreviousLectures',
        ),
        migrations.DeleteModel(
            name='PreviousWorkshops',
        ),
        migrations.RenameField(
            model_name='languagecourses',
            old_name='mode',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='languagecourses',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='languagecourses',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='languagecourses',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='languagecourses',
            name='location',
        ),
        migrations.RemoveField(
            model_name='languagecourses',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='languagecourses',
            name='url',
        ),
        migrations.AddField(
            model_name='languagecourses',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='languagecourses',
            name='register_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='languagecourses',
            name='resource_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='languagecourses',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='languagecourses',
            name='fees',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='languagecourses',
            name='photo',
            field=models.ImageField(blank=True, upload_to='language-courses/'),
        ),
    ]
