# Generated by Django 5.2.5 on 2026-04-24 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_delete_lectures_delete_previouslectures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('group', models.CharField(choices=[('pal', 'PAL'), ('ug-council', 'UG Council'), ('phd-council', 'PhD Council'), ('workshops', 'Workshops'), ('language', 'Language'), ('sab-team', 'SAB Team'), ('ric-team', 'RIC Team')], max_length=50)),
                ('certificate_type', models.CharField(choices=[('PAL', 'PAL Mentor'), ('BR', 'Branch Representative'), ('DUPC', 'DUPC Student Representative'), ('DPPC', 'DPPC Student Representative'), ('CPPC', 'CPPC Student Representative'), ('SPPC', 'SPPC Student Representative'), ('WORKSHOP', 'Workshop Course'), ('LANGUAGE', 'Language Course'), ('EC', 'Executive Committee'), ('RIC', 'RIC Executive Committee')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('session', models.CharField(help_text='Example: 2025-26', max_length=50)),
                ('issue_date', models.DateField()),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, editable=False, help_text='Automatically generated', max_length=20)),
                ('credential_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('public_code', models.SlugField(blank=True, max_length=150, unique=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificate_qr/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('BR', 'Branch Representatives'), ('DUPC', 'DUPC Data'), ('CERT', 'Certificate')], max_length=20)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dupc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dupc/')),
                ('tenure', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'DUPCs',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_url', models.URLField()),
                ('feedback_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RICCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('tenure', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ric_council/')),
            ],
            options={
                'verbose_name_plural': 'RICCouncil',
            },
        ),
        migrations.CreateModel(
            name='RICGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='ric_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
