# Generated by Django 5.2.5 on 2026-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_create_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchrepresentative',
            name='extra_por',
            field=models.TextField(blank=True, null=True),
        ),
        
    ]
