# Generated by Django 5.2.5 on 2026-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_branchrepresentative_extra_por_links_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupc',
            name='extra_por',
            field=models.TextField(blank=True, null=True),
        ),
        
        migrations.AddField(
            model_name='phdcppc',
            name='extra_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phddppc',
            name='extra_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phdsppc',
            name='extra_por',
            field=models.TextField(blank=True, null=True),
        ),
    ]
