# Generated by Django 5.2.5 on 2026-04-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_dupc_extra_por_links_id_phdcppc_extra_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_type',
            field=models.CharField(choices=[('BR', 'Branch Representatives'), ('DUPC', 'DUPC Data'), ('DPPC', 'DPPC Student Representatives'), ('CPPC', 'CPPC Student Representatives'), ('SPPC', 'SPPC Student Representatives')], max_length=20),
        ),
    ]
