# Generated by Django 5.2.5 on 2026-04-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_datarequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchrepresentative',
            name='role',
            field=models.CharField(default='Branch Representative', max_length=100),
        ),
        migrations.AddField(
            model_name='dupc',
            name='role',
            field=models.CharField(default='DUPC Representative', max_length=100),
        ),
        migrations.AddField(
            model_name='phdcppc',
            name='role',
            field=models.CharField(default='CPPC Representative', max_length=100),
        ),
        migrations.AddField(
            model_name='phddppc',
            name='role',
            field=models.CharField(default='DPPC Representative', max_length=100),
        ),
        migrations.AddField(
            model_name='phdsppc',
            name='role',
            field=models.CharField(default='SPPC Representative', max_length=100),
        ),
    ]
