# Generated by Django 5.2.5 on 2026-04-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_branchrepresentative_role_dupc_role_phdcppc_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('PAL', 'PAL Mentor'), ('BR', 'Branch Representative'), ('DUPC', 'DUPC Student Representative'), ('DPPC', 'DPPC Student Representative'), ('CPPC', 'CPPC Student Representative'), ('SPPC', 'SPPC Student Representative'), ('WORKSHOP', 'Workshop Course'), ('LANGUAGE', 'Language Course'), ('EC', 'SAB Executive Committee'), ('RIC', 'RIC Executive Committee')], max_length=20),
        ),
    ]
