# Generated by Django 5.2.5 on 2026-05-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_certificate_certificate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='signed_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('PAL', 'PAL Mentor'), ('BR', 'Branch Representative'), ('DUPC', 'DUPC Student Representative'), ('DPPC', 'DPPC Student Representative'), ('CPPC', 'CPPC Student Representative'), ('SPPC', 'SPPC Student Representative'), ('WORKSHOP', 'Workshop Course'), ('LANGUAGE', 'Language Course'), ('EC', 'SAB Executive Council'), ('RIC', 'RIC Executive Committee'), ('MENTOR', 'Mentor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='group',
            field=models.CharField(choices=[('pal', 'PAL'), ('ug-council', 'UG Council'), ('phd-council', 'PhD Council'), ('workshops', 'Workshops'), ('language', 'Language'), ('sab-team', 'SAB Team'), ('ric-team', 'RIC Team'), ('mentor', 'Mentor')], max_length=50),
        ),
    ]
