# Generated by Django 5.2.5 on 2026-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_certificate_signed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='extra_por',
            field=models.TextField(blank=True, null=True),
        ),
    ]
