# Generated by Django 5.2.5 on 2026-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_council_extra_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('tenure', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
