# Generated by Django 5.2.5 on 2026-05-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_gallerypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='image',
            field=models.ImageField(upload_to='gallery-page/'),
        ),
    ]
