# Generated by Django 5.2.5 on 2026-05-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_gallerypage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypage',
            options={'verbose_name_plural': 'GalleryPage'},
        ),
    ]
