# Generated by Django 5.2.5 on 2026-05-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_gallerypage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_type',
            field=models.CharField(choices=[('BR', 'Branch Representatives'), ('DUPC', 'DUPC Student Representatives'), ('DPPC', 'DPPC Student Representatives'), ('CPPC', 'CPPC Student Representatives'), ('SPPC', 'SPPC Student Representatives')], max_length=20),
        ),
    ]
